# -*- coding: utf-8 -*-
import requests
# Form implementation generated from reading ui file 'BMS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSettings
from PyQt5.QtWidgets import QWidget, QTreeWidgetItem, QLabel, QMessageBox




class Ui_BMS(object):

    def setupUi(self, BMS):
        print("3")
        BMS.setObjectName("BMS")
        BMS.resize(861, 592)
        BMS.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Singapore))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(BMS)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deviceLabel = QtWidgets.QLabel(BMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceLabel.sizePolicy().hasHeightForWidth())
        self.deviceLabel.setSizePolicy(sizePolicy)
        self.deviceLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.deviceLabel.setFont(font)
        self.deviceLabel.setObjectName("deviceLabel")
        self.verticalLayout.addWidget(self.deviceLabel)
        self.deviceTree = QtWidgets.QTreeWidget(BMS)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.deviceTree.setFont(font)
        self.deviceTree.setObjectName("deviceTree")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.deviceTree.headerItem().setFont(0, font)
        self.verticalLayout.addWidget(self.deviceTree)
        self.objectLabel = QtWidgets.QLabel(BMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectLabel.sizePolicy().hasHeightForWidth())
        self.objectLabel.setSizePolicy(sizePolicy)
        self.objectLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.objectLabel.setFont(font)
        self.objectLabel.setObjectName("objectLabel")
        self.verticalLayout.addWidget(self.objectLabel)
        self.objectList = QtWidgets.QListWidget(BMS)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.objectList.setFont(font)
        self.objectList.setObjectName("objectList")
        self.verticalLayout.addWidget(self.objectList)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instanceLabel = QtWidgets.QLabel(BMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instanceLabel.sizePolicy().hasHeightForWidth())
        self.instanceLabel.setSizePolicy(sizePolicy)
        self.instanceLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.instanceLabel.setFont(font)
        self.instanceLabel.setObjectName("instanceLabel")
        self.verticalLayout_2.addWidget(self.instanceLabel)
        self.instanceTable = QtWidgets.QTableWidget(BMS)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.instanceTable.setFont(font)
        self.instanceTable.setObjectName("instanceTable")
        self.instanceTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.instanceTable)
        self.diagramLabel = QtWidgets.QLabel(BMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diagramLabel.sizePolicy().hasHeightForWidth())
        self.diagramLabel.setSizePolicy(sizePolicy)
        self.diagramLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.diagramLabel.setFont(font)
        self.diagramLabel.setObjectName("diagramLabel")
        self.verticalLayout_2.addWidget(self.diagramLabel)
        self.diagramList = QtWidgets.QListWidget(BMS)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.diagramList.setFont(font)
        self.diagramList.setObjectName("diagramList")
        self.verticalLayout_2.addWidget(self.diagramList)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(BMS)
        QtCore.QMetaObject.connectSlotsByName(BMS)

        self.instanceTable.setColumnCount(4)
        self.instanceTable.setHorizontalHeaderLabels(["Show", "Device", "ObjectID", "Time"])
        print("1")
        self.Port_label = QLabel("Double-click to open UIConnector", self)
        self.deviceTree.setColumnCount(1)
        self.parent_item = QTreeWidgetItem(self.deviceTree)
        self.deviceTree.setItemWidget(self.parent_item, 0, self.Port_label)
        self.Port_label.mouseDoubleClickEvent = self.on_item_double_clicked

    def on_item_double_clicked(self,event):
        content=self.Port_label.text()
        if content == "Double-click to open UIConnector":
            self.start_connector()
        elif content == load_setting("id"):
            device_id=load_setting("id")
            try:
                        # 向后端发送连接请求
                        response = requests.get('http://127.0.0.1:5000/bms/device_objects',
                                                json={'device_id': device_id})
                        result = response.json()

                        for obj in result['objects']:
                            instance = obj.get('object_instance', None)
                            obj_type = obj.get('object_type', None)
                            self.objectList.addItem(f"{obj_type}: {instance}")
                            self.objectList.itemDoubleClicked.connect(self.on_content_double_clicked)

            except requests.ConnectionError:
                QMessageBox.critical(self, 'Error', 'Unable to connect to the server')

        else:
            return  # elif ":" in text:  #     obj_type, instance = text.split(":", 1)  #     if obj_type == "analogInput" and instance == "0":  #         print(1)  #     elif obj_type == "analogOutput" and instance == "1":  #         print(2)


    def retranslateUi(self, BMS):
        _translate = QtCore.QCoreApplication.translate
        BMS.setWindowTitle(_translate("BMS", "Form"))
        self.deviceLabel.setText(_translate("BMS", "Devices"))
        self.deviceTree.headerItem().setText(0, _translate("BMS", "Local IP Address: 0.0.0.0"))
        self.objectLabel.setText(_translate("BMS", "Objects"))
        self.instanceLabel.setText(_translate("BMS", "Instances"))
        self.diagramLabel.setText(_translate("BMS", "Diagrams"))

def load_setting(key):
    """
    通用的读取 QSettings 设置的函数，确保返回字符串
    :param key: 配置的键名，例如 'port', 'ip', 'device_id'
    :param default_value: 如果配置不存在时返回的默认值
    :return: 配置值，类型为字符串
    """
    settings = QSettings("MyCompany", "BMSApp")
    value = settings.value(key, "1111")  # 读取配置，如果没有则返回默认值
    return str(value)  # 确保返回的是字符串

import resources_rc
