# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMSDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BMSDialog(object):
    def setupUi(self, BMSDialog):
        BMSDialog.setObjectName("BMSDialog")
        BMSDialog.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BMSDialog.sizePolicy().hasHeightForWidth())
        BMSDialog.setSizePolicy(sizePolicy)
        BMSDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Singapore))
        self.buttonBox = QtWidgets.QDialogButtonBox(BMSDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(BMSDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 361, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.localPortLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.localPortLabel.setFont(font)
        self.localPortLabel.setObjectName("localPortLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.localPortLabel)
        self.localPortLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.localPortLineEdit.setInputMask("")
        self.localPortLineEdit.setMaxLength(6)
        self.localPortLineEdit.setObjectName("localPortLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.localPortLineEdit)
        self.remoteIPLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.remoteIPLabel.setFont(font)
        self.remoteIPLabel.setObjectName("remoteIPLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remoteIPLabel)
        self.remoteIPLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.remoteIPLineEdit.setMaxLength(20)
        self.remoteIPLineEdit.setObjectName("remoteIPLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remoteIPLineEdit)
        self.remotePortLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.remotePortLabel.setFont(font)
        self.remotePortLabel.setObjectName("remotePortLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.remotePortLabel)
        self.remotePortLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.remotePortLineEdit.setMaxLength(6)
        self.remotePortLineEdit.setObjectName("remotePortLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remotePortLineEdit)

        self.retranslateUi(BMSDialog)
        self.buttonBox.accepted.connect(BMSDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(BMSDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BMSDialog)

    def retranslateUi(self, BMSDialog):
        _translate = QtCore.QCoreApplication.translate
        BMSDialog.setWindowTitle(_translate("BMSDialog", "Connect to BMS"))
        self.localPortLabel.setText(_translate("BMSDialog", "Local Port:"))
        self.localPortLineEdit.setPlaceholderText(_translate("BMSDialog", "47808"))
        self.remoteIPLabel.setText(_translate("BMSDialog", "Remote IP:"))
        self.remotePortLabel.setText(_translate("BMSDialog", "Remote Port:"))
