# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connector(object):
    def setupUi(self, connector):
        connector.setObjectName("connector")
        connector.resize(394, 297)
        self.formLayout = QtWidgets.QFormLayout(connector)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(connector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Port_label = QtWidgets.QLabel(connector)
        self.Port_label.setObjectName("Port_label")
        self.horizontalLayout_2.addWidget(self.Port_label)
        self.lineEdit = QtWidgets.QLineEdit(connector)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.Start_button = QtWidgets.QPushButton(connector)
        self.Start_button.setObjectName("Start_button")
        self.horizontalLayout_2.addWidget(self.Start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Endpoint_label = QtWidgets.QLabel(connector)
        self.Endpoint_label.setObjectName("Endpoint_label")
        self.horizontalLayout.addWidget(self.Endpoint_label)
        self.lineEdit_3 = QtWidgets.QLineEdit(connector)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(connector)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(connector)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(connector)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(connector)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)

        self.retranslateUi(connector)
        QtCore.QMetaObject.connectSlotsByName(connector)

    def retranslateUi(self, connector):
        _translate = QtCore.QCoreApplication.translate
        connector.setWindowTitle(_translate("connector", "Form"))
        self.title_label.setText(_translate("connector", "BACnet/IP"))
        self.Port_label.setText(_translate("connector", "Device Port"))
        self.Start_button.setText(_translate("connector", "Start"))
        self.Endpoint_label.setText(_translate("connector", "Device IP"))
        self.label.setText(_translate("connector", "Local Port"))
        self.label_2.setText(_translate("connector", "Local IP"))
