# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.bms_main import Ui_main

class Ui_connector(object):
    def setupUi(self, connector):
        connector.setObjectName("connector")
        connector.resize(312, 92)
        self.formLayout = QtWidgets.QFormLayout(connector)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(connector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Port_label = QtWidgets.QLabel(connector)
        self.Port_label.setObjectName("Port_label")
        self.horizontalLayout_2.addWidget(self.Port_label)
        self.lineEdit = QtWidgets.QLineEdit(connector)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.Start_button = QtWidgets.QPushButton(connector)
        self.Start_button.setObjectName("Start_button")
        self.horizontalLayout_2.addWidget(self.Start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Endpoint_label = QtWidgets.QLabel(connector)
        self.Endpoint_label.setObjectName("Endpoint_label")
        self.horizontalLayout.addWidget(self.Endpoint_label)
        self.IP_combo = QtWidgets.QComboBox(connector)
        self.IP_combo.setObjectName("IP_combo")
        self.horizontalLayout.addWidget(self.IP_combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)
        self.Start_button.clicked.connect(self.goto_bms_main)
        self.retranslateUi(connector)
        self.Start_button.clicked.connect(connector.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(connector)

    def retranslateUi(self, connector):
        _translate = QtCore.QCoreApplication.translate
        connector.setWindowTitle(_translate("connector", "Form"))
        self.title_label.setText(_translate("connector", "BACnet/IP"))
        self.Port_label.setText(_translate("connector", "Port"))
        self.Start_button.setText(_translate("connector", "Start"))
        self.Endpoint_label.setText(_translate("connector", "Local Endpoint"))

    def goto_bms_main(self):
        self.bms_main = QtWidgets.QWidget()  # 创建一个主窗口
        self.ui = Ui_main()  # 创建 UI 实例
        self.ui.setupUi(self.bms_main)  # 将 UI 设置到主窗口上
        self.bms_main.show()  # 显示主窗口